set -g default-terminal "xterm-kitty"
set -ag terminal-overrides ",xterm-kitty:RGB"
set -ag terminal-features ",xterm-kitty:hyperlinks"

set -g mouse on
set -g history-limit 10000
set -s escape-time 0          # no delay for ESC key (penting untuk vim/neovim)
set -g focus-events on        # focus events untuk vim autoread
set -g base-index 1           # window mulai dari 1
setw -g pane-base-index 1     # pane mulai dari 1
set -g renumber-windows on    # renumber otomatis saat window ditutup

set -g bell-action none
set -g visual-bell off
set -g visual-activity off

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

setw -g mode-keys vi
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

set -g status on
set -g status-interval 5
set -g status-position bottom
set -g status-justify left

set -g status-style "bg=#101315,fg=#cacccc"

set -g status-left-length 30
set -g status-left "#[bg=#de6145,fg=#101315,bold] #S #[bg=#101315,fg=#de6145]"

set -g status-right-length 60
set -g status-right "#[fg=#4b4e55]#[bg=#4b4e55,fg=#9a9a9a] %H:%M #[bg=#4b4e55,fg=#565d60]#[bg=#565d60,fg=#cacccc] #h "

setw -g window-status-style "bg=#101315,fg=#4b4e55"
setw -g window-status-format " #I #W "

setw -g window-status-current-style "bg=#4b4e55,fg=#cacccc,bold"
setw -g window-status-current-format "#[bg=#798186,fg=#101315] #I #[bg=#4b4e55,fg=#cacccc] #W "

set -g pane-border-style "fg=#4b4e55"
set -g pane-active-border-style "fg=#798186"

set -g message-style "bg=#4b4e55,fg=#cacccc"
set -g message-command-style "bg=#4b4e55,fg=#de6145"

setw -g mode-style "bg=#798186,fg=#101315"

set -g set-titles on
set -g set-titles-string "#S · #W"

new-session -d -s main
