general {
    hide_cursor = false
}

background {
    monitor =
    path =
    color = rgb(1e1e2e)
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgb(b4befe)
    font_size = 46
    font_family = FiraCode Nerd Font Mono Bold
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color = rgb(bac2de)
    font_size = 15
    font_family = FiraCode Nerd Font Mono Bold
    position = 0, 50
    halign = center
    valign = center
}

label {
    monitor =
    text = Password required to continue...
    color = rgb(7f849c)
    font_size = 12
    font_family = FiraCode Nerd Font Mono Bold
    position = 0, -75
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 480, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgb(cba6f7)
    inner_color = rgb(11111b)
    font_color = rgb(a6e3a1)
    font_family = FiraCode Nerd Font Mono Bold
    placeholder_text = <span foreground="##6c7086">$ </span><span foreground="##7f849c">type your password_</span>
    hide_input = false
    rounding = 0
    check_color = rgb(a6e3a1)
    fail_color = rgb(f38ba8)
    fail_text = <span foreground="##f38ba8">[!] authentication failed: $FAIL</span>
    capslock_color = rgb(fab387)
    fade_on_empty = false
    position = 0, -130
    halign = center
    valign = center
}

label {
    monitor =
    text = Press [Enter] to submit — [Esc] to clear
    color = rgb(6c7086)
    font_size = 11
    font_family = FiraCode Nerd Font Mono Bold
    position = 0, -190
    halign = center
    valign = center
}
