require("modules.autostart")
require("modules.binds")
require("modules.env")
require("modules.input")
require("modules.looknfeel")
require("modules.misc")
require("modules.monitors")
require("modules.windowrule")
