general {
    hide_cursor        = true
    ignore_empty_input = true
}

background {
    monitor    =
    color      = rgba(101315ff)
    blur_passes = 0
    blur_size   = 0
    noise       = 0.0
    contrast    = 1.0
    brightness  = 1.0
    vibrancy    = 0.0
    vibrancy_darkness = 0.0
}

input-field {
    monitor  =
    size     = 300, 52

    outline_thickness = 1
    dots_size         = 0.28
    dots_spacing      = 0.18
    dots_center       = true
    dots_rounding     = -1

    outer_color  = rgba(4b4e55ff)
    inner_color  = rgba(1a1e21ff)
    font_color   = rgba(cacccoff)

    fade_on_empty    = false
    fade_timeout     = 1000
    placeholder_text = <span foreground="##565d60">enter password...</span>
    hide_input       = false
    rounding         = 10

    check_color = rgba(798186ff)
    fail_color  = rgba(de6145ff)
    fail_text   = <i>$FAIL <b>($ATTEMPTS)</b></i>

    position = 0, 0
    halign   = center
    valign   = center
}
