[flavor]
use = ""

[manager]
cwd = { fg = "#798186", bold = true }

hovered         = { fg = "#101315", bg = "#798186", bold = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#d9dbdc", bold = true, italic = true, underline = true }
find_position = { fg = "#aeaeae", bold = true, italic = true }

marker_copied   = { fg = "#9fa5a9", bg = "#9fa5a9" }
marker_cut      = { fg = "#de6145", bg = "#de6145" }
marker_marked   = { fg = "#aeaeae", bg = "#aeaeae" }
marker_selected = { fg = "#798186", bg = "#798186" }

tab_active   = { fg = "#101315", bg = "#798186", bold = true }
tab_inactive = { fg = "#9fa5a9", bg = "#1a1e21" }

count_copied   = { fg = "#101315", bg = "#9fa5a9" }
count_cut      = { fg = "#101315", bg = "#de6145" }
border_symbol  = "│"
border_style   = { fg = "#343d41" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#343d41", bg = "#101315" }

mode_normal = { fg = "#101315", bg = "#798186", bold = true }
mode_select = { fg = "#101315", bg = "#9fa5a9", bold = true }
mode_unset  = { fg = "#101315", bg = "#aeaeae", bold = true }

progress_label  = { fg = "#cacccc", bold = true }
progress_normal = { fg = "#798186", bg = "#343d41" }
progress_error  = { fg = "#de6145", bg = "#343d41" }

perm_type  = { fg = "#798186" }
perm_read  = { fg = "#d9dbdc" }
perm_write = { fg = "#de6145" }
perm_exec  = { fg = "#9fa5a9" }
perm_sep   = { fg = "#565d60" }

[input]
border   = { fg = "#798186" }
title    = { fg = "#798186" }
value    = { fg = "#cacccc" }
selected = { reversed = true }

[completion]
border   = { fg = "#343d41" }
active   = { fg = "#101315", bg = "#798186" }
inactive = { fg = "#9fa5a9" }

[tasks]
border  = { fg = "#343d41" }
title   = { fg = "#798186" }
hovered = { underline = true }

[which]
mask            = { bg = "#1a1e21" }
cand            = { fg = "#9fa5a9" }
rest            = { fg = "#565d60" }
desc            = { fg = "#aeaeae" }
separator       = "  "
separator_style = { fg = "#343d41" }

[help]
on      = { fg = "#798186" }
run     = { fg = "#aeaeae" }
hovered = { bg = "#343d41", bold = true }
footer  = { fg = "#101315", bg = "#798186" }

[notify]
title_info  = { fg = "#798186" }
title_warn  = { fg = "#d9dbdc" }
title_error = { fg = "#de6145" }
icon_info   = ""
icon_warn   = ""
icon_error  = ""

[filetype]

rules = [
  { mime = "image/*", fg = "#9fa5a9" },
  { mime = "video/*", fg = "#aeaeae" },
  { mime = "audio/*", fg = "#707070" },
  { mime = "application/zip",              fg = "#d9dbdc" },
  { mime = "application/gzip",             fg = "#d9dbdc" },
  { mime = "application/x-tar",            fg = "#d9dbdc" },
  { mime = "application/x-bzip*",          fg = "#d9dbdc" },
  { mime = "application/x-7z-compressed",  fg = "#d9dbdc" },
  { mime = "application/x-rar",            fg = "#d9dbdc" },
  { mime = "application/xz",               fg = "#d9dbdc" },
  { mime = "application/pdf",              fg = "#de6145" },
  { mime = "application/msword",           fg = "#798186" },
  { mime = "application/vnd.*",            fg = "#798186" },
  { mime = "text/*",                       fg = "#9fa5a9" },
  { mime = "application/x-shellscript", fg = "#a5aeb4" },
  { mime = "text/x-shellscript",        fg = "#a5aeb4" },
  { mime = "*",  fg = "#cacccc" },
]
