music_directory    "/home/hi/Music"
playlist_directory "/home/hi/.config/mpd/playlists"
db_file            "/home/hi/.config/mpd/database"
log_file           "/home/hi/.config/mpd/log"
pid_file           "/home/hi/.config/mpd/pid"
state_file         "/home/hi/.config/mpd/state"
sticker_file       "/home/hi/.config/mpd/sticker.sql"

bind_to_address    "127.0.0.1"
port               "6600"
